[package]
published-at = "0xaa168c61e541e29f3ba20fe13c5a27f13fb8858fb11373167012e132fbc64401"
name = "world"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet", override = true }
entity = { local = "../entity" }
components = { local = "../components" }
systems = { local = "../systems" }

[addresses]
world = "0xaa168c61e541e29f3ba20fe13c5a27f13fb8858fb11373167012e132fbc64401"
