[package]
name = "systems"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet", override = true }
entity = { local = "../entity" }
components = { local = "../components" }

[addresses]
systems = "0x0"

